### ISSUE TITLE
ModuleNotFoundError: No module named 'jmespath'

### ISSUE THREAD

**Issue by mondalanindya** [yang326922943/VIP-Versatile-Image-Outpainting-Empowered-by-Multimodal-Large-Language-Model#2]
I am getting the following error even after installing the correct dependencies:

`Traceback (most recent call last):
  File "/home/amondal/.local/bin/accelerate", line 5, in <module>
    from accelerate.commands.accelerate_cli import main
  File "/home/amondal/.local/lib/python3.8/site-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/home/amondal/.local/lib/python3.8/site-packages/accelerate/accelerator.py", line 31, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/home/amondal/.local/lib/python3.8/site-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/home/amondal/.local/lib/python3.8/site-packages/accelerate/utils/__init__.py", line 106, in <module>
    from .launch import (
  File "/home/amondal/.local/lib/python3.8/site-packages/accelerate/utils/launch.py", line 24, in <module>
    from ..commands.config.config_args import SageMakerConfig
  File "/home/amondal/.local/lib/python3.8/site-packages/accelerate/commands/config/__init__.py", line 19, in <module>
    from .config import config_command_parser
  File "/home/amondal/.local/lib/python3.8/site-packages/accelerate/commands/config/config.py", line 25, in <module>
    from .sagemaker import get_sagemaker_input
  File "/home/amondal/.local/lib/python3.8/site-packages/accelerate/commands/config/sagemaker.py", line 35, in <module>
    import boto3  # noqa: F401
  File "/home/amondal/.local/lib/python3.8/site-packages/boto3/__init__.py", line 17, in <module>
    from boto3.session import Session
  File "/home/amondal/.local/lib/python3.8/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/home/amondal/.local/lib/python3.8/site-packages/botocore/session.py", line 26, in <module>
    import botocore.client
  File "/home/amondal/.local/lib/python3.8/site-packages/botocore/client.py", line 15, in <module>
    from botocore import waiter, xform_name
  File "/home/amondal/.local/lib/python3.8/site-packages/botocore/waiter.py", line 16, in <module>
    import jmespath
ModuleNotFoundError: No module named 'jmespath'`

**Comment by ucasyjz** [comment]
Sorry, i may need more information about the error
